<?php require_once 'templates/layout/header.phtml'; ?>
<?php require_once 'templates/form_videojuegos.phtml'; ?>

<?php if(!empty($videogamesWithPlatforms)): ?>

<table>
    <thead>
        <th>id_juego</th>
        <th>Nombre</th>
        <th>Desarrollador</th>
        <th>Distribuidor</th>
        <th>Género</th>
        <th>Fecha de lanzamiento</th>
        <th>Plataforma</th>
        <th>Modos de juego</th>
        <th>Precio</th>
    </thead>
    <?php foreach($videogamesWithPlatforms as $videogameWithPlatform): ?>
        <tr>
        <td><?=$videogameWithPlatform->id_juego?></td>
            <td><?=$videogameWithPlatform->nombre?></td>
            <td><?=$videogameWithPlatform->desarrollador?></td>
            <td><?=$videogameWithPlatform->distribuidor?></td>
            <td><?=$videogameWithPlatform->genero?></td>
            <td><?=$videogameWithPlatform->fecha_lanzamiento?></td>
            <td><?=$videogameWithPlatform->plataforma?></td>
            <td><?=$videogameWithPlatform->modos_de_juego?></td>
            <td><?=$videogameWithPlatform->precio?></td>
            <td>
                <a href="manage-videogames/edit-videogame/<?= $videogameWithPlatform->id_juego ?>" type="button" class='btn btn-danger ml-auto'>Editar</a>
            </td>
            <td>
                <a href="delete_videogame/<?= $videogameWithPlatform->id_juego ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<?php else: ?>
    <p>No existe ningún item.</p>
<?php endif ?>


<?php require_once 'templates/layout/footer.phtml'; ?>